name: Generate Snake

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: vinayakkam
          outputs: |
            dist/github-snake.svg?palette=github&color_snake=E03C3C&color_dots=#ff6b6b,#e03c3c,#c0392b,#922b21,#641e16
            dist/github-snake-dark.svg?color_snake=E03C3C&color_dots=#ff6b6b,#e03c3c,#c0392b,#922b21,#641e16

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
